name: Macrocosm
main: space.maxus.macrocosm.InternalMacrocosmPlugin
version: 0.1-SNAPSHOT
api-version: 1.19
libraries:
    - "net.axay:kspigot:1.19.0"
    - "org.postgresql:postgresql:42.3.6"
    - "org.xerial:sqlite-jdbc:3.36.0.3"
    - "io.ktor:ktor-server-core-jvm:2.1.0"
    - "io.ktor:ktor-server-netty-jvm:2.1.0"
    - "io.ktor:ktor-server-default-headers-jvm:2.1.0"
    - "io.ktor:ktor-server-status-pages-jvm:2.1.0"
    - "org.jetbrains.exposed:exposed-core:0.39.2"
    - "org.jetbrains.exposed:exposed-jdbc:0.39.2"
    - "org.jetbrains.exposed:exposed-dao:0.39.2"
    - "net.dv8tion:JDA:5.0.0-alpha.18"
    - "club.minnced:discord-webhooks:0.8.2"
depend: [ ProtocolLib, LibsDisguises ]
load: POSTWORLD
