name: Macrocosm
main: space.maxus.macrocosm.InternalMacrocosmPlugin
version: 0.1-SNAPSHOT
api-version: 1.19
libraries:
    - "net.axay:kspigot:1.19.2"
    - "org.postgresql:postgresql:42.3.6"
    - "io.ktor:ktor-server-core-jvm:2.2.1"
    - "io.ktor:ktor-server-netty-jvm:2.2.1"
    - "io.ktor:ktor-server-default-headers-jvm:2.2.1"
    - "io.ktor:ktor-server-status-pages-jvm:2.2.1"
    - "net.dv8tion:JDA:5.0.0-beta.2"
    - "club.minnced:discord-webhooks:0.8.2"
    - "org.litote.kmongo:kmongo:4.8.0"
    - "io.prometheus:simpleclient:0.16.0"
    - "io.prometheus:simpleclient_httpserver:0.16.0"
    - "io.ktor:ktor-client-core:2.3.0"
    - "io.ktor:ktor-client-java-jvm:2.3.0"
depend: [ ProtocolLib, LibsDisguises ]
load: POSTWORLD
