name: Macrocosm
main: space.maxus.macrocosm.InternalMacrocosmPlugin
version: 0.1-SNAPSHOT
api-version: 1.18
libraries:
    - "net.axay:kspigot:1.18.2"
    - "com.dropbox.core:dropbox-core-sdk:5.2.0"
depend: [ ProtocolLib, LibsDisguises ]
