name: Docs
on:
    push:
        branches: [master]
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    Publish-Docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17
            - name: Build documentation
              run: ./gradlew dokkaHtml
            - name: Relocate documentation
              run: mv build/dokka/html/* docs
            - name: Setup pages
              run: actions/configure-pages@v2
            - name: Upload page artifact
              uses: actions/upload-pages-artifact@v1
              with:
                path: 'docs'
                cname: macrocosm.maxus.space
            - name: Publish documentation
              id: deployment
              uses: actions@deploy-pages@v1
